#undefine EPSINF
#undefine GLM
#undefine EXTRAFLAGS
#define STAGGERED
#undefine FCT
#undefine NORMINIT
#undefine HALL
#undefine UCONVERT
#undefine SAVENOW
#undefine TRANSFORMW
#undefine RAY
#undefine BIGENDIAN
#undefine FOURTHORDER
#undefine TCRKL2
#undefine TCPERPENDICULAR
#undefine SPECIALTOLERANCE
#undefine MAGNETOFRICTION
#undefine PARTICLES
#undefine PARTICLES_ADVECT
#undefine BOUNDARYDRIVER
#undefine HDF5
#define ENTROPY
